# Generated by Django 3.1.3 on 2021-03-08 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(default='', max_length=63)),
                ('date_of_birth', models.DateField()),
                ('city', models.CharField(default='', max_length=63)),
                ('country', models.CharField(default='', max_length=127)),
                ('member_type', models.CharField(choices=[('g', 'General Member'), ('l', 'Lifetime Member'), ('s', 'Super Admin'), ('a', 'Admin')], default='', max_length=24)),
                ('is_active', models.CharField(default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Members',
            },
        ),
    ]
